/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cafeteria.view;

import cafeteria.dao.EmployeeDAO;
import cafeteria.utils.Auth;
import cafeteria.utils.MsgBox;

import javax.swing.*;
import java.awt.event.KeyEvent;

public class ChangePasswordView extends javax.swing.JInternalFrame {

	private static final long serialVersionUID = 1L;
    EmployeeDAO nhanVienDAO = new EmployeeDAO();
    
    public ChangePasswordView() {
        initComponents();
        txtUser.setText(Auth.user.getMaNhanVien());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ckbHienThi = new javax.swing.JCheckBox();
        btnXacNhan = new javax.swing.JButton();
        txtPassCu = new JPasswordField();
        txtPassMoi2 = new JPasswordField();
        txtPassMoi = new JPasswordField();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Đổi mật khẩu");

        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("UserName");

        txtUser.setEditable(false);

        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("Mật khẩu cũ");

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Mật khẩu mới");

        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("Xác nhận mật khẩu mới");

        ckbHienThi.setText("Hiển thị mật khẩu");
        ckbHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ckbHienThiActionPerformed(evt);
            }
        });

        btnXacNhan.setBackground(new java.awt.Color(0, 0, 255));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        txtPassMoi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(KeyEvent evt) {
                txtPassMoi2KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPassMoi)
                    .addComponent(txtPassMoi2)
                    .addComponent(txtPassCu)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ckbHienThi))
                    .addComponent(txtUser, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(0, 125, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassMoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ckbHienThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("ĐỔI MẬT KHẨU");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String maNv = txtUser.getText();
        String matKhau = new String(txtPassCu.getPassword());
        String matKhauMoi = new String(txtPassMoi.getPassword());
        String matKhauMoi2 = new String(txtPassMoi2.getPassword());
       
        if (isError(matKhau, matKhauMoi, matKhauMoi2)) 
            return;
        changePassword();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void ckbHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ckbHienThiActionPerformed
        if (ckbHienThi.isSelected()) {
            showPassword(txtPassCu,txtPassMoi,txtPassMoi2);
        } else {
            hidePassword(txtPassCu,txtPassMoi,txtPassMoi2);
        }
    }//GEN-LAST:event_ckbHienThiActionPerformed

    private void txtPassMoi2KeyPressed(KeyEvent evt) {//GEN-FIRST:event_txtPassMoi2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String maNv = txtUser.getText();
            String matKhau = new String(txtPassCu.getPassword());
            String matKhauMoi = new String(txtPassMoi.getPassword());
            String matKhauMoi2 = new String(txtPassMoi2.getPassword());
       
            if (isError(matKhau, matKhauMoi, matKhauMoi2)) 
                return;
            changePassword();
        }
    }//GEN-LAST:event_txtPassMoi2KeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JCheckBox ckbHienThi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private JPasswordField txtPassCu;
    private JPasswordField txtPassMoi;
    private JPasswordField txtPassMoi2;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables

    private boolean isError(String matKhauCu,String matKhauMoi, String xacNhanMatKhau) {
        if (isEmpty(matKhauCu,matKhauMoi, xacNhanMatKhau)) {
            MsgBox.notify("Mật khẩu không được trống", this);
            return true;
        }
        
        if (!isGreater8Char(matKhauMoi, xacNhanMatKhau)) {
            MsgBox.notify("Mật khẩu phải dài hơn 8 ký tự", this);
            return true;
        }
        
        if (!isMatch(matKhauMoi, xacNhanMatKhau)) {
            MsgBox.notify("Mật khẩu mới và xác nhận mật khẩu không trùng nhau", this);
            return true;
        }
        return false;
    }
    
    private boolean isEmpty(String matkhaucu,String matKhau, String xacNhanMatKhau) {
        return (matKhau.isEmpty() || xacNhanMatKhau.isEmpty() || matkhaucu.isEmpty());
    }
    
    private boolean isGreater8Char(String matKhau, String xacNhanMatKhau) {
        return (matKhau.length() >= 8 && xacNhanMatKhau.length() >= 8);
    }
    
    private boolean isMatch(String matKhauMoi, String xacNhanMatKhau) {
        return matKhauMoi.equals(xacNhanMatKhau);
    }
    
    private void changePassword() {
        Auth.user.setMatKhau(txtPassMoi.getText());
        try {
            nhanVienDAO.update(Auth.user);
            MsgBox.notify("Đổi mật khẩu thành công", this);
        } catch (Exception e) {
            MsgBox.notify("lỗi", this);
        }
    }
    
    private void showPassword(JPasswordField...pass) {
        for (JPasswordField x : pass)
            x.setEchoChar('\u0000');
    }
    
     private void hidePassword(JPasswordField...pass) {
        for (JPasswordField x : pass)
            x.setEchoChar('\u25cf');
    }
}
